### ISSUE TITLE
Task Discussions

### ISSUE THREAD

**Issue by GammaMicrowave** [GeekHaven/WebD-Selection-23-24-Final-Tasks#1]
For any queries regarding the task add a comment in this issue.

**Comment by BuddyLongLegs** [comment]
Creating a backend or using any other API is **NOT** allowed in this task, you have to achieve every feature using frontend ONLY. If you are trying to do the 8th Dessert feature, then also you shall **NOT** create a backend, you will store the new section or questions in the frontend Local Storage only, as only the user who is adding new questions/sections shall see them in their own device only.

**Comment by VatsalBhuva11** [comment]
@BuddyLongLegs @GammaMicrowave I've created the site, will try the dessert section now. Just wanted to confirm whether this is how the site should be, so that I can continue further. Please have a look at the GitHub pages in my repo (added you as collaborators). Thanks.

**Comment by Manas2403** [comment]
> @BuddyLongLegs @GammaMicrowave I've created the site, will try the dessert section now. Just wanted to confirm whether this is how the site should be, so that I can continue further. Please have a look at the GitHub pages in my repo (added you as collaborators). Thanks.

All the repositories will be evaluated once after the deadline.Till then complete the task by your understanding

**Comment by BuddyLongLegs** [comment]
You can take a look on existing DSA sheets available on the internet for reference to get to know how a DSA sheet looks like.

**Comment by atharva-gadekar** [comment]
Everyone who has completed the task must update their project's live link in the Google Form. Only projects with the live links in the original Google Form would be considered for evaluation.
